import {
  GET_POSTS_SUCCESS,
  GET_POSTS_FAILURE,
  fetchGetPosts,
} from './Sample';

import {
  GET_PRODUCTS_SUCCESS,
  GET_PRODUCTS_FAILURE,
  fetchGetProducts,
  POST_CREATE_PRODUCTS_SUCCESS,
  POST_CREATE_PRODUCTS_FAILURE,
  fetchCreateProducts,
  CLEAR_CREATE_PRODUCTS_SUCCESS,
  CLEAR_CREATE_PRODUCTS_FAILURE,
  clearCreateProducts,
  DELETE_PRODUCTS_SUCCESS,
  DELETE_PRODUCTS_FAILURE,
  deleteProducts,
  CLEAR_DELETE_PRODUCTS_SUCCESS,
  CLEAR_DELETE_PRODUCTS_FAILURE,
  clearDeleteProducts,
} from './Products';

import {
  GET_ORDERS_SUCCESS,
  GET_ORDERS_FAILURE,
  fetchGetOrders,
  POST_SERVE_ORDERS_SUCCESS,
  POST_SERVE_ORDERS_FAILURE,
  fetchServeOrders,
  CLEAR_SERVE_ORDERS_SUCCESS,
  CLEAR_SERVE_ORDERS_FAILURE,
  clearServeOrders,
} from './Orders';

export {
  // sample
  GET_POSTS_SUCCESS,
  GET_POSTS_FAILURE,
  fetchGetPosts,
  // products
  GET_PRODUCTS_SUCCESS,
  GET_PRODUCTS_FAILURE,
  fetchGetProducts,
  POST_CREATE_PRODUCTS_SUCCESS,
  POST_CREATE_PRODUCTS_FAILURE,
  fetchCreateProducts,
  CLEAR_CREATE_PRODUCTS_SUCCESS,
  CLEAR_CREATE_PRODUCTS_FAILURE,
  clearCreateProducts,
  DELETE_PRODUCTS_SUCCESS,
  DELETE_PRODUCTS_FAILURE,
  deleteProducts,
  CLEAR_DELETE_PRODUCTS_SUCCESS,
  CLEAR_DELETE_PRODUCTS_FAILURE,
  clearDeleteProducts,
  // orders
  GET_ORDERS_SUCCESS,
  GET_ORDERS_FAILURE,
  fetchGetOrders,
  POST_SERVE_ORDERS_SUCCESS,
  POST_SERVE_ORDERS_FAILURE,
  fetchServeOrders,
  CLEAR_SERVE_ORDERS_SUCCESS,
  CLEAR_SERVE_ORDERS_FAILURE,
  clearServeOrders,
};
